routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index');
Route::get('/category/{id}', 'HomeController@category');
Route::get('/change-password', 'Auth\ChangePasswordController@showChangePasswordForm');
Route::post('/change-password', 'Auth\ChangePasswordController@changePassword');

Route::resource('feeds', 'FeedsController');
Route::resource('feed-categories', 'FeedCategoriesController');

app/FeedCategory.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class FeedCategory
 * @package App
 */
class FeedCategory extends Model
{
    /** @var array */
    protected $fillable = [
        'title',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function feeds()
    {
        return $this->hasMany(Feed::class);
    }
}

app/Http/Controllers/FeedCategoriesController.php
<?php
namespace App\Http\Controllers;

use App\FeedCategory;
use App\Http\Requests;
use App\Http\Requests\FeedCategoriesRequest;
use Session;

/**
 * Class FeedCategoriesController
 * @package App\Http\Controllers
 */
class FeedCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $categories = FeedCategory::all();

        return view('feed_categories.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('feed_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param FeedCategoriesRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(FeedCategoriesRequest $request)
    {
        $input = $request->all();
        FeedCategory::create($input);

        Session::flash('flash_message', 'Category successfully added!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        /** @var FeedCategory $category */
        $category = FeedCategory::findOrFail($id);
        $feeds = $category->feeds()->getResults();

        return view('feed_categories.show',
            [
                'category' => $category,
                'feeds' => $feeds,
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        /** @var FeedCategory $category */
        $category = FeedCategory::findOrFail($id);

        return view('feed_categories.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param FeedCategoriesRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(FeedCategoriesRequest $request, $id)
    {
        /** @var FeedCategory $category */
        $category = FeedCategory::findOrFail($id);
        $input = $request->all();
        $category->fill($input)->save();

        Session::flash('flash_message', 'Category successfully updated!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        /** @var FeedCategory $category */
        $category = FeedCategory::findOrFail($id);
        $category->feeds()->delete();
        $category->delete();

        Session::flash('flash_message', 'Category successfully deleted!');
        return redirect()->route('feed-categories.index');
    }
}

resources/views/feed_categories/create.blade.php
@extends('layouts.feed-category')

@section('content_category')
    <h1>Add a new category</h1>
    <p class="lead">Add to your categories list below.</p>
    <hr>
    @include('errors.form_errors')
    {!! Form::open(['route' => 'feed-categories.store']) !!}

    <div class="form-group">
        {!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>

    {!! Form::submit('Create new category', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@stop

resources/views/feed_categories/edit.blade.php
@extends('layouts.feed-category')

@section('content_category')

    <h1>Editing "{{ $category->title }}"</h1>
    <p class="lead">Edit this category below, or <a href="{{ route('feed-categories.index') }}">go back to all categories.</a></p>
    <hr>

    @include('errors.form_errors')
    {!! Form::model($category, [
        'method' => 'PATCH',
        'route' => ['feed-categories.update', $category->id]
    ]) !!}

    <div class="form-group">
        {!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>

    {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@stop

resources/views/feed_categories/index.blade.php
@extends('layouts.feed-category')

@section('content_category')
    @foreach($categories as $category)
        <h3>{{ $category->title }}</h3>
        <p>
            <a href="{{ route('feed-categories.show', $category->id) }}" class="btn btn-info">View</a>
            <a href="{{ route('feed-categories.edit', $category->id) }}" class="btn btn-primary">Edit</a>
        </p>
        <hr>
    @endforeach
@stop

resources/views/feed_categories/show.blade.php
@extends('layouts.feed-category')

@section('content_category')
    <h1>Category "{{ $category->title }}"</h1>
    <hr>

    <div class="row">
        <div class="col-md-6">
            <a href="{{ route('feed-categories.index') }}" class="btn btn-info">Back to all categories</a>
            <a href="{{ route('feed-categories.edit', $category->id) }}" class="btn btn-primary">Edit category</a>
        </div>
        <div class="col-md-6 text-right">
            {!! Form::open([
                'method' => 'DELETE',
                'route' => ['feed-categories.destroy', $category->id]
            ]) !!}
            {!! Form::submit('Delete this category?', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>
    </div>
    @if (count($feeds))
        <div class="row">
            <h2>In category "{{ $category->title }}" existing feeds</h2>
            <div class="col-md-6">
                @foreach($feeds as $feed)
                    <h3>{{ $feed->title }}, {{ $feed->url }}</h3>
                    <p>
                        <a href="{{ route('feed-categories.show', $feed->id) }}" class="btn btn-info">View</a>
                        <a href="{{ route('feed-categories.edit', $feed->id) }}" class="btn btn-primary">Edit</a>
                    </p>
                    <hr>
                @endforeach
            </div>
        </div>
    @endif
@stop